apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgA/jaa71F4lLOeZwBQQgWP58irs8BqtyJI5ccjPZkN36Bigkh8HmcPyh+ko8PtQnManPpoOV3HQvspAvLX/xxUYadEXIcb6U418SL8AXsSqFpXoqWzSRlJQevkXg1z6Fmef7SUq5VRaseEMomsxchJ53DfENIMvvDD4Ofn7V18+aAcpWyU71uNnfsRPwabfaYDF4+cdIL10FW/CGMFyI4ndXPk/Oo4pDnIlcEiowdh5r20xy5xyUTR3BT6zX/zp9sUxAPhYlde7Az7ugfRD+EHTFMV/XZtGvU4Rvu1wj6WqOHa6M6xM9AmcasAqh9KZlivkfWJQMNMqbbLXLDPF2lhZkPOhA9wBEG0emousivu7Ql8xDvzYtoEfsmt4S+qSTp8QyBJN2/N12PuHJy6pdxdLgjIT9t+ZWY1GguMD14Th+kOW1ubyiX5cD3wklpSZweB0FQ7SHuaqfVvDIpH19tsqyHHw1iIeEAeN0WfjZBJi9wGjWvIk5ML14jZ6cmjC2sOKlgj+KAiMlNdL+HwYrylBiFhfCH0s0atuU4ZoNzsa/Qk9hSlFwgfMPAep9jk9ez7xzG45aa/pgadrqBW1RyxkyMbMmApoaXUcaP+WC2bdHwQxMaQ0JiR+v743FHMkShsXXkIcdqgP1u38H8M1rIyUuM+JahMPyccMtNrUnjWjeNd85c1c0eHuJ8DnbMn6ORb95R4ibFQXIGfRy0jwXUmg4Jib6hKVMFdacHeGx7CcZZL0mF+I+IZH
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

